### ISSUE TITLE
paris feature not working

### ISSUE THREAD

**Issue by TheBotlyNoob** [Drakulix/simplelog.rs#91]
not sure if i'm doing something wrong, but when I try:
```toml
# Cargo.toml
[dependencies]
simplelog = { version = "0.11", features = ["paris"] }
```

```rust
// ...
fn main() {
  simplelog::CombinedLogger::init(vec![
    simplelog::TermLogger::new(
      simplelog::LevelFilter::Debug,
      simplelog::Config::default(),
      simplelog::TerminalMode::Mixed,
      simplelog::ColorChoice::Auto,
    ),
    simplelog::WriteLogger::new(
      simplelog::LevelFilter::Debug,
      simplelog::Config::default(),
      std::fs::File::create("my_rust_binary.log").unwrap(),
    ),
  ])
  .expect("Failed to start simplelog");

  info!("I can write <b>bold</b> text or use tags to <red>color it</>");
}
```

it outputs: `02:33:51 [INFO] I can write <b>bold</b> text or use tags to <red>color it</>`
